#!/bin/sh

start() {
	echo heartbeat > /sys/class/leds/led0/trigger
}

stop() {
	echo none > /sys/class/leds/led0/trigger
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac

